### PR TITLE
GCC MACRO-11 output example

### PR DESCRIPTION
**Pull request by jaylogue**
- Updated Dockerfile to pull, build and install macro11 assembler from https://gitlab.com/Rhialto/macro11.

- Updated Dockerfile to install GNU make using apt-get.

- Created example application showing how to compile C code to MACRO-11 assembly, assemble it using macro11 and convert it to absolute loader format.

### CODE REVIEW

**Comment by jaylogue** [comment]
Hey @JamesHagerman,

Here is my first pass at adding an example for MACRO-11 output.  I have tested the build steps as a increments on your image, but I have yet to do a full image build top-to-bottom.  I am also thinking I'll add a README to the example; just didn't have time to finish it tonight.  I'll update the PR when I'm ready.

**Comment by JamesHagerman** [comment]
@jaylogue Awesome! Thank you for contributing!

I tried getting Docker Hub to build your branch but I couldn't figure it out. Don't worry about the build though, it'll either pass or fail when the PR is merged anyways.

I'll hold off on merging this until you add a readme. And I'll let you know if I can get it to build in the meantime.

**Review by JamesHagerman — APPROVED** [review]

**Comment by jaylogue** [comment]
I've forced pushed a new commit that adds the README and fixes an issue with the generated absolute-loader image.

If you're happy with it, I think this is ready to merge.

**Comment by jaylogue** [comment]
@JamesHagerman : Hey James, any chance you can merge this?  Thanks.

**Comment by JamesHagerman** [comment]
🤦‍♂ Sorry for the long delay on this! Life is... a thing.

Thank you for the contribution! I'll work to get a new Docker image built!

**Comment by JamesHagerman** [comment]
Build is running on Dockerhub now! The last build took 240 minutes to complete on Docker's build infrastructure! 😱

It should create a tag when it's finished. If it doesn't or if the build fails I'll post back here to let you know.

**Pull request merged**
